apiVersion: apps/v1
kind: Deployment
metadata:
  name: marai-backend
  labels:
    app: marai-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marai-backend
  template:
    metadata:
      labels:
        app: marai-backend
    spec:
      containers:
      - name: marai-backend
        image: marai-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: marai-backend-service
spec:
  selector:
    app: marai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort