apiVersion: apps/v1
kind: Deployment
metadata:
  name: marai-client
  labels:
    app: marai-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marai-client
  template:
    metadata:
      labels:
        app: marai-client
    spec:
      containers:
      - name: marai-client
        image: marai-client-reactjs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: marai-client-service
spec:
  selector:
    app: marai-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort